# Generated by Django 4.2 on 2025-01-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('E', 'Elèctrico'), ('A', 'Agua'), ('F', 'Fuego'), ('T', 'Tierra'), ('P', 'Planta')], max_length=30),
        ),
    ]
